# Generated by Django 4.2.30 on 2026-07-13 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema')),
                ('paleta_cores', models.CharField(choices=[('default', 'Padrão (Azul)'), ('forest', 'Floresta (Verde)'), ('sunset', 'Pôr do Sol (Laranja)'), ('ocean', 'Oceano (Turquesa)'), ('lavender', 'Lavanda (Roxo)'), ('ruby', 'Rubi (Vermelho)')], default='default', max_length=20, verbose_name='Paleta de Cores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
